const animals=[
["Lion","Panthera leo","Mammal","Savanna","Carnivore","🦁","Social big cat known for prides and powerful hunting."],
["Tiger","Panthera tigris","Mammal","Forest","Carnivore","🐅","Largest living cat species; usually solitary."],
["Cheetah","Acinonyx jubatus","Mammal","Grassland","Carnivore","🐆","Specialized for short bursts of high-speed running."],
["Leopard","Panthera pardus","Mammal","Forest","Carnivore","🐆","Adaptable cat and skilled climber that often stores prey in trees."],
["Jaguar","Panthera onca","Mammal","Rainforest","Carnivore","🐆","Powerful American cat with a strong bite."],
["Snow Leopard","Panthera uncia","Mammal","Mountains","Carnivore","🐆","Mountain cat with a long tail for balance and warmth."],
["Domestic Cat","Felis catus","Mammal","Human environments","Carnivore","🐈","Small domesticated feline with excellent hearing and agility."],
["Gray Wolf","Canis lupus","Mammal","Forests","Carnivore","🐺","Highly social canine that lives and hunts in packs."],
["Red Fox","Vulpes vulpes","Mammal","Grassland","Omnivore","🦊","Adaptable fox found across much of the Northern Hemisphere."],
["Brown Bear","Ursus arctos","Mammal","Forests","Omnivore","🐻","Large bear whose diet ranges from plants to fish and mammals."],
["Giant Panda","Ailuropoda melanoleuca","Mammal","Mountain forest","Herbivore","🐼","Bear famous for its bamboo-heavy diet."],
["Polar Bear","Ursus maritimus","Mammal","Arctic sea ice","Carnivore","🐻‍❄️","Marine-associated bear specialized for Arctic life."],
["Asian Elephant","Elephas maximus","Mammal","Forest","Herbivore","🐘","Large herbivore with a trunk and complex social behavior."],
["African Savanna Elephant","Loxodonta africana","Mammal","Savanna","Herbivore","🐘","Largest living land animal."],
["Giraffe","Giraffa camelopardalis","Mammal","Savanna","Herbivore","🦒","Tall browser with a long neck and specialized cardiovascular system."],
["Zebra","Equus quagga","Mammal","Grassland","Herbivore","🦓","Striped grazing mammal of eastern and southern Africa."],
["Horse","Equus caballus","Mammal","Grassland","Herbivore","🐎","Domesticated hoofed mammal used worldwide for transport, sport and companionship."],
["Cow","Bos taurus","Mammal","Grassland","Herbivore","🐄","Domesticated ruminant raised for food, fiber and other products."],
["Goat","Capra hircus","Mammal","Mountains","Herbivore","🐐","Hardy domesticated ruminant able to browse many plants."],
["Sheep","Ovis aries","Mammal","Grassland","Herbivore","🐑","Domesticated ruminant widely raised for wool, meat and milk."],
["Pig","Sus scrofa domesticus","Mammal","Human environments","Omnivore","🐖","Domesticated relative of the wild boar with a strong sense of smell."],
["Capybara","Hydrochoerus hydrochaeris","Mammal","Wetlands","Herbivore","🦫","World's largest living rodent; highly social and semi-aquatic."],
["Beaver","Castor canadensis","Mammal","Wetlands","Herbivore","🦫","Rodent famous for building dams and altering waterways."],
["Rabbit","Oryctolagus cuniculus","Mammal","Grassland","Herbivore","🐇","Fast-breeding herbivore with powerful hind legs."],
["Koala","Phascolarctos cinereus","Mammal","Eucalyptus forest","Herbivore","🐨","Australian marsupial that feeds mainly on eucalyptus leaves."],
["Kangaroo","Osphranter rufus","Mammal","Desert","Herbivore","🦘","Large Australian marsupial that moves with powerful hopping."],
["Platypus","Ornithorhynchus anatinus","Mammal","Freshwater","Carnivore","🦆","Egg-laying mammal with a duck-like bill and webbed feet."],
["Blue Whale","Balaenoptera musculus","Mammal","Ocean","Carnivore","🐋","Largest known animal, feeding mainly on tiny krill."],
["Humpback Whale","Megaptera novaeangliae","Mammal","Ocean","Carnivore","🐋","Known for long migrations and complex songs."],
["Bottlenose Dolphin","Tursiops truncatus","Mammal","Ocean","Carnivore","🐬","Intelligent toothed dolphin that uses echolocation."],
["Bat","Chiroptera","Mammal","Caves","Insectivore","🦇","Only mammals capable of true powered flight."],
["Sloth","Bradypus variegatus","Mammal","Rainforest","Herbivore","🦥","Slow-moving tree-dweller adapted to life in the canopy."],
["Chimpanzee","Pan troglodytes","Mammal","Rainforest","Omnivore","🐒","Highly social great ape capable of tool use."],
["Gorilla","Gorilla gorilla","Mammal","Rainforest","Herbivore","🦍","Large great ape living in family groups led by a dominant male."],
["Eagle","Aquila chrysaetos","Bird","Mountains","Carnivore","🦅","Powerful raptor with excellent eyesight."],
["Bald Eagle","Haliaeetus leucocephalus","Bird","Wetlands","Carnivore","🦅","Fish-eating North American eagle."],
["Owl","Strigiformes","Bird","Forest","Carnivore","🦉","Nocturnal raptors with specialized hearing and silent flight."],
["Penguin","Sphenisciformes","Bird","Polar coast","Carnivore","🐧","Flightless seabirds adapted for swimming."],
["Emperor Penguin","Aptenodytes forsteri","Bird","Antarctica","Carnivore","🐧","Largest penguin species and breeder on Antarctic winter ice."],
["Ostrich","Struthio camelus","Bird","Savanna","Omnivore","🦤","Largest living bird and a powerful runner."],
["Flamingo","Phoenicopterus roseus","Bird","Wetlands","Omnivore","🦩","Wading bird famous for pink plumage and filter feeding."],
["Peacock","Pavo cristatus","Bird","Forest","Omnivore","🦚","Peafowl known for the male's elaborate display feathers."],
["Parrot","Psittaciformes","Bird","Rainforest","Omnivore","🦜","Group of intelligent birds with curved bills and strong feet."],
["Toucan","Ramphastidae","Bird","Rainforest","Omnivore","🦜","Tropical bird family recognized for large colorful bills."],
["Hummingbird","Trochilidae","Bird","Forest","Nectarivore","🐦","Tiny birds capable of hovering and rapid wingbeats."],
["Crow","Corvus","Bird","Woodland","Omnivore","🐦‍⬛","Highly adaptable and intelligent birds in the corvid family."],
["Chicken","Gallus gallus domesticus","Bird","Human environments","Omnivore","🐔","Domesticated bird kept worldwide for eggs and meat."],
["Crocodile","Crocodylus","Reptile","Wetlands","Carnivore","🐊","Semi-aquatic reptile with powerful jaws and armored skin."],
["Komodo Dragon","Varanus komodoensis","Reptile","Island","Carnivore","🦎","Largest living lizard, native to several Indonesian islands."],
["Green Iguana","Iguana iguana","Reptile","Rainforest","Herbivore","🦎","Large arboreal lizard that mainly eats vegetation."],
["Chameleon","Chamaeleonidae","Reptile","Forest","Insectivore","🦎","Lizards known for independently moving eyes and specialized tongues."],
["King Cobra","Ophiophagus hannah","Reptile","Forest","Carnivore","🐍","Large venomous snake that mainly eats other snakes."],
["Python","Pythonidae","Reptile","Forest","Carnivore","🐍","Nonvenomous constricting snakes that subdue prey by squeezing."],
["Sea Turtle","Chelonioidea","Reptile","Ocean","Omnivore","🐢","Marine turtles that return to land to lay eggs."],
["Galápagos Tortoise","Chelonoidis","Reptile","Island","Herbivore","🐢","Long-lived giant tortoises native to the Galápagos Islands."],
["Axolotl","Ambystoma mexicanum","Amphibian","Freshwater","Carnivore","🦎","Aquatic salamander famous for retaining juvenile features as an adult."],
["Frog","Anura","Amphibian","Wetlands","Insectivore","🐸","Broad amphibian group with powerful jumping and diverse lifestyles."],
["Salamander","Caudata","Amphibian","Forest","Carnivore","🦎","Amphibians with tails, including aquatic and terrestrial species."],
["Clownfish","Amphiprioninae","Fish","Coral reef","Omnivore","🐠","Small reef fish famous for living among sea anemones."],
["Great White Shark","Carcharodon carcharias","Fish","Ocean","Carnivore","🦈","Large predatory shark found in temperate and coastal waters."],
["Hammerhead Shark","Sphyrnidae","Fish","Ocean","Carnivore","🦈","Sharks with a distinctive flattened head shape."],
["Manta Ray","Mobulidae","Fish","Ocean","Planktivore","🪽","Large rays that filter-feed on plankton."],
["Seahorse","Hippocampus","Fish","Seagrass","Carnivore","🐴","Small fish in which males carry developing young in a brood pouch."],
["Goldfish","Carassius auratus","Fish","Freshwater","Omnivore","🐟","Domesticated freshwater fish descended from East Asian carp."],
["Piranha","Pygocentrus","Fish","Freshwater","Omnivore","🐟","South American freshwater fish with strong jaws and teeth."],
["Salmon","Salmo salar","Fish","River/Ocean","Carnivore","🐟","Migratory fish that can travel between ocean and freshwater."],
["Octopus","Octopoda","Invertebrate","Ocean","Carnivore","🐙","Eight-armed mollusk known for camouflage, problem solving and flexible bodies."],
["Giant Squid","Architeuthis dux","Invertebrate","Deep ocean","Carnivore","🦑","Large deep-sea cephalopod with enormous eyes."],
["Jellyfish","Medusozoa","Invertebrate","Ocean","Carnivore","🪼","Stinging aquatic animals with a bell-shaped body in many species."],
["Starfish","Asteroidea","Invertebrate","Ocean","Carnivore","⭐","Marine echinoderms with radial body plans and regenerative abilities."],
["Sea Urchin","Echinoidea","Invertebrate","Ocean","Herbivore","🦔","Spiny echinoderms that often graze algae from rocky surfaces."],
["Crab","Brachyura","Invertebrate","Ocean","Omnivore","🦀","Decapod crustaceans with a broad body and strong claws in many species."],
["Lobster","Nephropidae","Invertebrate","Ocean","Omnivore","🦞","Large marine crustaceans with powerful claws in many species."],
["Honey Bee","Apis mellifera","Invertebrate","Grassland","Herbivore","🐝","Social insect important for pollination and honey production."],
["Butterfly","Lepidoptera","Invertebrate","Flowering plants","Herbivore","🦋","Winged insects with a complete metamorphosis from caterpillar to adult."],
["Ant","Formicidae","Invertebrate","Soil","Omnivore","🐜","Highly social insects living in colonies with specialized roles."],
["Praying Mantis","Mantodea","Invertebrate","Grassland","Carnivore","🦗","Predatory insect with grasping forelegs."],
["Dragonfly","Odonata","Invertebrate","Wetlands","Carnivore","🪰","Fast-flying insects whose young develop in water."],
["Tarantula","Theraphosidae","Invertebrate","Forest","Carnivore","🕷️","Large hairy spiders that use venom to subdue prey."],
["Scorpion","Scorpiones","Invertebrate","Desert","Carnivore","🦂","Arachnids with pincers and a venomous tail in most species."]
];

const grid=document.querySelector("#grid"),input=document.querySelector("#search"),count=document.querySelector("#count"),empty=document.querySelector("#empty");
function render(q=""){const x=q.trim().toLowerCase();const found=animals.filter(a=>a.join(" ").toLowerCase().includes(x));count.textContent=found.length+" species";grid.innerHTML=found.map(a=>`<article class="card"><div class="icon">${a[5]}</div><h3>${a[0]}</h3><div class="scientific">${a[1]}</div><div class="tags"><span class="tag">${a[2]}</span><span class="tag">${a[4]}</span></div><div class="facts"><span>📍 ${a[3]}</span><span>ℹ️ ${a[6]}</span></div></article>`).join("");empty.hidden=found.length>0}
input.addEventListener("input",()=>render(input.value));document.querySelector("#clear").onclick=()=>{input.value="";render();input.focus()};document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{input.value=b.dataset.q;render(b.dataset.q);document.querySelector("#explore").scrollIntoView({behavior:"smooth"})});document.querySelector("#menuBtn").onclick=()=>document.querySelector("nav").style.display=document.querySelector("nav").style.display==="flex"?"none":"flex";render();