const raw=[
"🦁|Lion|Panthera leo|Mammal|Savanna|Carnivore|Social big cat known for prides and powerful hunting.|pride,roars",
"🐅|Tiger|Panthera tigris|Mammal|Forest|Carnivore|Largest living cat species; usually solitary.|stripes,swimming",
"🐆|Cheetah|Acinonyx jubatus|Mammal|Grassland|Carnivore|Specialized for short bursts of high-speed running.|speed",
"🐆|Leopard|Panthera pardus|Mammal|Forest|Carnivore|Adaptable cat and skilled climber that often stores prey in trees.|spots,climbing",
"🐆|Jaguar|Panthera onca|Mammal|Rainforest|Carnivore|Powerful American cat with an exceptionally strong bite.|spots,swimming",
"🐺|Gray Wolf|Canis lupus|Mammal|Forest|Carnivore|Highly social canine that lives and hunts in packs.|pack,howling",
"🦊|Red Fox|Vulpes vulpes|Mammal|Grassland|Omnivore|Adaptable fox found across much of the Northern Hemisphere.|nocturnal",
"🐻|Brown Bear|Ursus arctos|Mammal|Forest|Omnivore|Large bear whose diet ranges from plants to fish and mammals.|hibernation",
"🐼|Giant Panda|Ailuropoda melanoleuca|Mammal|Mountain forest|Herbivore|Bear famous for its bamboo-heavy diet.|bamboo",
"🐻‍❄️|Polar Bear|Ursus maritimus|Mammal|Arctic|Carnivore|Marine-associated bear specialized for Arctic life.|ice,swimming",
"🐘|African Elephant|Loxodonta africana|Mammal|Savanna|Herbivore|Largest living land animal.|trunk,herd",
"🐘|Asian Elephant|Elephas maximus|Mammal|Forest|Herbivore|Large herbivore with a trunk and complex social behavior.|trunk,herd",
"🦒|Giraffe|Giraffa camelopardalis|Mammal|Savanna|Herbivore|Tall browser with a long neck and specialized cardiovascular system.|tall,spots",
"🦓|Zebra|Equus quagga|Mammal|Grassland|Herbivore|Striped grazing mammal of eastern and southern Africa.|stripes,herd",
"🦏|White Rhinoceros|Ceratotherium simum|Mammal|Grassland|Herbivore|Large grazing rhinoceros with two horns.|horn,grazing",
"🦏|Black Rhinoceros|Diceros bicornis|Mammal|Savanna|Herbivore|Browser with a pointed upper lip and two horns.|horn,browser",
"🦛|Hippopotamus|Hippopotamus amphibius|Mammal|River|Herbivore|Large semi-aquatic mammal that spends much of its day in water.|river,territorial",
"🦒|Okapi|Okapia johnstoni|Mammal|Rainforest|Herbivore|Forest relative of the giraffe with striped legs.|stripes,forest",
"🐎|Horse|Equus caballus|Mammal|Grassland|Herbivore|Domesticated hoofed mammal used worldwide for transport and sport.|domestic,herd",
"🐄|Cow|Bos taurus|Mammal|Grassland|Herbivore|Domesticated ruminant raised worldwide.|ruminant,domestic",
"🐐|Goat|Capra hircus|Mammal|Mountains|Herbivore|Hardy domesticated ruminant able to browse many plants.|climbing,domestic",
"🐑|Sheep|Ovis aries|Mammal|Grassland|Herbivore|Domesticated ruminant widely raised for wool and meat.|wool,flock",
"🐖|Pig|Sus scrofa domesticus|Mammal|Human environments|Omnivore|Domesticated relative of the wild boar with a strong sense of smell.|domestic,smell",
"🦫|Capybara|Hydrochoerus hydrochaeris|Mammal|Wetlands|Herbivore|World's largest living rodent; highly social and semi-aquatic.|social,swimming",
"🦫|Beaver|Castor canadensis|Mammal|Wetlands|Herbivore|Rodent famous for building dams and changing waterways.|dams,teeth",
"🐇|Rabbit|Oryctolagus cuniculus|Mammal|Grassland|Herbivore|Fast-moving herbivore with powerful hind legs.|burrow,jumping",
"🐨|Koala|Phascolarctos cinereus|Mammal|Eucalyptus forest|Herbivore|Australian marsupial that feeds mainly on eucalyptus leaves.|marsupial,eucalyptus",
"🦘|Red Kangaroo|Osphranter rufus|Mammal|Desert|Herbivore|Large Australian marsupial that moves by powerful hopping.|hopping,marsupial",
"🦘|Wallaby|Notamacropus|Mammal|Forest|Herbivore|Common name for several smaller kangaroo relatives.|marsupial,hopping",
"🦆|Platypus|Ornithorhynchus anatinus|Mammal|Freshwater|Carnivore|Egg-laying mammal with a duck-like bill and webbed feet.|eggs,venom",
"🐋|Blue Whale|Balaenoptera musculus|Mammal|Ocean|Planktivore|Largest known animal, feeding mainly on tiny krill.|largest,krill",
"🐋|Humpback Whale|Megaptera novaeangliae|Mammal|Ocean|Carnivore|Known for long migrations and complex songs.|songs,migration",
"🐬|Bottlenose Dolphin|Tursiops truncatus|Mammal|Ocean|Carnivore|Intelligent toothed dolphin that uses echolocation.|echolocation,social",
"🦭|Harbor Seal|Phoca vitulina|Mammal|Coast|Carnivore|Coastal seal that rests on rocks and beaches.|marine,diving",
"🦦|Sea Otter|Enhydra lutris|Mammal|Coast|Carnivore|Marine mammal that often uses rocks as tools to open prey.|tools,kelp",
"🦇|Bat|Chiroptera|Mammal|Caves|Insectivore|Only mammals capable of true powered flight.|flight,echolocation",
"🦥|Sloth|Bradypus|Mammal|Rainforest|Herbivore|Slow-moving tree-dweller adapted to life in the canopy.|slow,trees",
"🐒|Chimpanzee|Pan troglodytes|Mammal|Rainforest|Omnivore|Highly social great ape capable of tool use.|tools,social",
"🦍|Gorilla|Gorilla|Mammal|Rainforest|Herbivore|Large great ape living in family groups.|ape,forest",
"🦧|Orangutan|Pongo|Mammal|Rainforest|Omnivore|Great ape known for arboreal life and problem solving.|trees,ape",
"🐒|Ring-tailed Lemur|Lemur catta|Mammal|Forest|Omnivore|Social primate recognized by its long black-and-white tail.|tail,social",
"🐿️|Red Squirrel|Sciurus vulgaris|Mammal|Forest|Herbivore|Tree squirrel that stores food and leaps between branches.|trees,nuts",
"🦔|European Hedgehog|Erinaceus europaeus|Mammal|Grassland|Insectivore|Small spiny mammal that often forages at night.|spines,nocturnal",
"🦡|Honey Badger|Mellivora capensis|Mammal|Savanna|Omnivore|Stocky mustelid with thick skin and a varied diet.|burrow,bold",
"🦁|Meerkat|Suricata suricatta|Mammal|Desert|Omnivore|Social mongoose that takes turns acting as a lookout.|sentinel,burrow",
"🦅|Bald Eagle|Haliaeetus leucocephalus|Bird|Wetlands|Carnivore|Fish-eating North American eagle.|fish,raptor",
"🦅|Golden Eagle|Aquila chrysaetos|Bird|Mountains|Carnivore|Powerful raptor with excellent eyesight.|raptor,flight",
"🦉|Barn Owl|Tyto alba|Bird|Grassland|Carnivore|Nocturnal owl with a heart-shaped facial disc.|nocturnal,silent",
"🦉|Snowy Owl|Bubo scandiacus|Bird|Arctic|Carnivore|Large white owl adapted to northern open habitats.|Arctic,feathers",
"🐧|Emperor Penguin|Aptenodytes forsteri|Bird|Antarctica|Carnivore|Largest penguin species and breeder on Antarctic winter ice.|Antarctica,diving",
"🐧|King Penguin|Aptenodytes patagonicus|Bird|Subantarctic|Carnivore|Large penguin with bright orange-yellow neck markings.|penguin,coast",
"🦩|Greater Flamingo|Phoenicopterus roseus|Bird|Wetlands|Omnivore|Wading bird famous for pink plumage and filter feeding.|pink,filter-feeding",
"🦚|Indian Peafowl|Pavo cristatus|Bird|Forest|Omnivore|Peafowl known for the male's elaborate display feathers.|display,feathers",
"🦜|Scarlet Macaw|Ara macao|Bird|Rainforest|Herbivore|Colorful parrot with a strong curved bill.|parrot,rainforest",
"🦜|African Grey Parrot|Psittacus erithacus|Bird|Rainforest|Herbivore|Intelligent parrot known for vocal learning.|intelligent,parrot",
"🐦|Common Raven|Corvus corax|Bird|Mountains|Omnivore|Large corvid known for intelligence and problem solving.|corvid,intelligent",
"🐦‍⬛|American Crow|Corvus brachyrhynchos|Bird|Woodland|Omnivore|Highly adaptable and social corvid.|corvid,adaptable",
"🐦|Peregrine Falcon|Falco peregrinus|Bird|Cliffs|Carnivore|Fast-flying falcon that hunts birds in flight.|speed,raptor",
"🦤|Ostrich|Struthio camelus|Bird|Savanna|Omnivore|Largest living bird and a powerful runner.|running,largest",
"🐦|Kiwi|Apteryx|Bird|Forest|Omnivore|Flightless nocturnal bird native to New Zealand.|nocturnal,flightless",
"🦤|Emu|Dromaius novaehollandiae|Bird|Grassland|Omnivore|Large flightless Australian bird.|running,Australia",
"🐔|Chicken|Gallus gallus domesticus|Bird|Human environments|Omnivore|Domesticated bird kept worldwide.|domestic,eggs",
"🦆|Mallard|Anas platyrhynchos|Bird|Wetlands|Omnivore|Widespread dabbling duck found across the Northern Hemisphere.|duck,wetlands",
"🦅|Harpy Eagle|Harpia harpyja|Bird|Rainforest|Carnivore|Powerful forest eagle with large talons.|rainforest,raptor",
"🐊|Nile Crocodile|Crocodylus niloticus|Reptile|River|Carnivore|Large African crocodilian with powerful jaws.|river,ambush",
"🐊|American Alligator|Alligator mississippiensis|Reptile|Wetlands|Carnivore|Large North American crocodilian found in freshwater habitats.|swamp,ambush",
"🐉|Komodo Dragon|Varanus komodoensis|Reptile|Island|Carnivore|Largest living lizard, native to Indonesian islands.|lizard,venom",
"🦎|Green Iguana|Iguana iguana|Reptile|Rainforest|Herbivore|Large arboreal lizard that mainly eats vegetation.|lizard,trees",
"🦎|Veiled Chameleon|Chamaeleo calyptratus|Reptile|Forest|Insectivore|Chameleon with a prominent casque and specialized tongue.|chameleon,tongue",
"🐍|King Cobra|Ophiophagus hannah|Reptile|Forest|Carnivore|Large venomous snake that mainly eats other snakes.|venom,snake",
"🐍|Ball Python|Python regius|Reptile|Grassland|Carnivore|Nonvenomous constrictor known for curling into a ball when threatened.|constrictor,pet",
"🐍|Green Anaconda|Eunectes murinus|Reptile|Wetlands|Carnivore|Massive semi-aquatic boa of South America.|snake,swimming",
"🐢|Green Sea Turtle|Chelonia mydas|Reptile|Ocean|Herbivore|Marine turtle whose adults often graze seagrasses and algae.|turtle,ocean",
"🐢|Galápagos Tortoise|Chelonoidis|Reptile|Island|Herbivore|Long-lived giant tortoises native to the Galápagos Islands.|giant,long-lived",
"🦎|Gila Monster|Heloderma suspectum|Reptile|Desert|Carnivore|Venomous lizard of the southwestern United States and Mexico.|venom,desert",
"🐸|Axolotl|Ambystoma mexicanum|Amphibian|Freshwater|Carnivore|Aquatic salamander famous for retaining juvenile features as an adult.|regeneration,salamander",
"🐸|Red-eyed Tree Frog|Agalychnis callidryas|Amphibian|Rainforest|Insectivore|Colorful arboreal frog with striking red eyes.|frog,trees",
"🐸|Poison Dart Frog|Dendrobatidae|Amphibian|Rainforest|Insectivore|Small brightly colored frogs; toxicity varies by species and diet.|frog,venom",
"🦎|Fire Salamander|Salamandra salamandra|Amphibian|Forest|Insectivore|Black-and-yellow salamander associated with moist forests.|salamander,forest",
"🐸|American Bullfrog|Lithobates catesbeianus|Amphibian|Wetlands|Carnivore|Large frog with a deep call and broad diet.|frog,wetlands",
"🐟|Great White Shark|Carcharodon carcharias|Fish|Ocean|Carnivore|Large predatory shark found in temperate and coastal waters.|shark,teeth",
"🦈|Hammerhead Shark|Sphyrnidae|Fish|Ocean|Carnivore|Sharks with a distinctive flattened head shape.|shark,head",
"🪽|Manta Ray|Mobulidae|Fish|Ocean|Planktivore|Large rays that filter-feed on plankton.|ray,filter-feeding",
"🐴|Seahorse|Hippocampus|Fish|Seagrass|Carnivore|Small fish in which males carry developing young in a brood pouch.|fish,pouch",
"🐠|Clownfish|Amphiprioninae|Fish|Coral reef|Omnivore|Small reef fish famous for living among sea anemones.|reef,anemone",
"🐟|Atlantic Salmon|Salmo salar|Fish|River/Ocean|Carnivore|Migratory fish that travels between ocean and freshwater.|migration,river",
"🐟|Goldfish|Carassius auratus|Fish|Freshwater|Omnivore|Domesticated freshwater fish descended from East Asian carp.|domestic,pond",
"🐟|Piranha|Pygocentrus|Fish|Freshwater|Omnivore|South American freshwater fish with strong jaws and teeth.|teeth,river",
"🐡|Pufferfish|Tetraodontidae|Fish|Ocean|Omnivore|Fish able to inflate its body when threatened; some contain powerful toxins.|inflation,toxin",
"🐟|Electric Eel|Electrophorus|Fish|Freshwater|Carnivore|South American knifefish capable of producing strong electric discharges.|electric,river",
"🐙|Giant Pacific Octopus|Enteroctopus dofleini|Invertebrate|Ocean|Carnivore|Large octopus known for camouflage and flexible problem solving.|octopus,camouflage",
"🦑|Giant Squid|Architeuthis dux|Invertebrate|Deep ocean|Carnivore|Large deep-sea cephalopod with enormous eyes.|deep-sea,eyes",
"🪼|Moon Jellyfish|Aurelia|Invertebrate|Ocean|Carnivore|Common jellyfish with a translucent bell and drifting lifestyle.|jellyfish,plankton",
"⭐|Common Starfish|Asterias rubens|Invertebrate|Ocean|Carnivore|Marine echinoderm with a five-armed body plan.|starfish,regeneration",
"🦔|Sea Urchin|Echinoidea|Invertebrate|Ocean|Herbivore|Spiny echinoderms that often graze algae from rocks.|spines,algae",
"🦀|Blue Crab|Callinectes sapidus|Invertebrate|Estuary|Omnivore|Swimming crab with paddle-like rear legs.|crab,estuary",
"🦞|American Lobster|Homarus americanus|Invertebrate|Ocean|Omnivore|Large marine crustacean with powerful claws.|claws,crustacean",
"🦐|Mantis Shrimp|Stomatopoda|Invertebrate|Coral reef|Carnivore|Marine crustacean with extraordinarily fast striking appendages.|reef,strike",
"🐝|Honey Bee|Apis mellifera|Invertebrate|Flowering plants|Herbivore|Social insect important for pollination and honey production.|bees,pollination",
"🦋|Monarch Butterfly|Danaus plexippus|Invertebrate|Grassland|Herbivore|Butterfly famous for long-distance seasonal migration.|migration,butterfly",
"🦋|Atlas Moth|Attacus atlas|Invertebrate|Forest|Herbivore|One of the world's largest moths by wing area.|moth,large",
"🐜|Leafcutter Ant|Atta|Invertebrate|Rainforest|Herbivore|Ants that harvest leaves to cultivate fungus in colonies.|ants,fungus",
"🦗|Praying Mantis|Mantodea|Invertebrate|Grassland|Carnivore|Predatory insect with grasping forelegs.|insect,predator",
"🪰|Dragonfly|Odonata|Invertebrate|Wetlands|Carnivore|Fast-flying insects whose young develop in water.|flight,water",
"🕷️|Tarantula|Theraphosidae|Invertebrate|Forest|Carnivore|Large hairy spiders that use venom to subdue prey.|spider,venom",
"🦂|Scorpion|Scorpiones|Invertebrate|Desert|Carnivore|Arachnids with pincers and a venomous tail in most species.|arachnid,venom",
"🐌|Giant African Land Snail|Achatina fulica|Invertebrate|Tropical forest|Herbivore|Large land snail that feeds on many kinds of vegetation.|snail,land",
"🪱|Earthworm|Lumbricidae|Invertebrate|Soil|Detritivore|Burrowing annelid that helps mix and aerate soil.|soil,decomposer",
"🦑|Nautilus|Nautilus|Invertebrate|Ocean|Carnivore|Cephalopod with a chambered external shell.|shell,cephalopod",
"🪸|Coral|Anthozoa|Invertebrate|Coral reef|Omnivore|Colonial cnidarians that can build reefs over long periods.|reef,polyps"
];
const animals=raw.map(x=>{const[a,b,c,d,e,f,g,h]=x.split("|");return{icon:a,name:b,sci:c,group:d,habitat:e,diet:f,desc:g,traits:h.split(",")}});

const input=document.querySelector("#search"),grid=document.querySelector("#grid"),count=document.querySelector("#count"),empty=document.querySelector("#empty"),suggestions=document.querySelector("#suggestions"),status=document.querySelector("#searchStatus");let active=-1;
function norm(s){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim()}
function score(a,q){if(!q)return 0;const n=norm(q), name=norm(a.name), sci=norm(a.sci), all=norm([a.name,a.sci,a.group,a.habitat,a.diet,a.desc,a.traits.join(" ")].join(" "));let s=0;if(name===n)s+=100;if(name.startsWith(n))s+=60;if(name.includes(n))s+=35;if(sci.includes(n))s+=25;if(all.includes(n))s+=10;for(const w of n.split(/\s+/))if(w.length>2&&all.includes(w))s+=4;return s}
function search(q){const n=norm(q);return animals.map(a=>({a,s:score(a,n)})).filter(x=>!n||x.s>0).sort((x,y)=>y.s-x.s||x.a.name.localeCompare(y.a.name)).map(x=>x.a)}
function render(q=""){const found=search(q);grid.innerHTML=found.map(a=>`<article class="card"><div class="icon">${a.icon}</div><h3>${a.name}</h3><div class="scientific">${a.sci}</div><div class="tags"><span class="tag">${a.group}</span><span class="tag">${a.diet}</span></div><p class="description">${a.desc}</p><div class="facts"><span>📍 ${a.habitat}</span>${a.traits.slice(0,2).map(t=>`<span>• ${t}</span>`).join("")}</div></article>`).join("");count.textContent=found.length+" animals";empty.hidden=found.length>0;status.textContent=q?("Results for “"+q+"”"):("Showing all "+animals.length+" profiles")}
function showSuggestions(q){if(!q.trim()){suggestions.hidden=true;return}const found=search(q).slice(0,7);suggestions.innerHTML=found.map((a,i)=>`<button class="suggestion${i===active?" active":""}" data-name="${a.name}"><span class="sicon">${a.icon}</span><span><b>${a.name}</b><small>${a.group} • ${a.habitat}</small></span></button>`).join("");suggestions.hidden=found.length===0;suggestions.querySelectorAll(".suggestion").forEach(b=>b.onclick=()=>{input.value=b.dataset.name;active=-1;suggestions.hidden=true;render(input.value);document.querySelector("#explore").scrollIntoView({behavior:"smooth"})})}
input.addEventListener("input",()=>{active=-1;render(input.value);showSuggestions(input.value)});input.addEventListener("keydown",e=>{const items=[...suggestions.querySelectorAll(".suggestion")];if(e.key==="ArrowDown"&&items.length){e.preventDefault();active=(active+1)%items.length;showSuggestions(input.value)}if(e.key==="ArrowUp"&&items.length){e.preventDefault();active=(active-1+items.length)%items.length;showSuggestions(input.value)}if(e.key==="Enter"&&items[active]){items[active].click()}if(e.key==="Escape"){suggestions.hidden=true}});document.addEventListener("click",e=>{if(!e.target.closest(".search-wrap"))suggestions.hidden=true});document.querySelector("#clear").onclick=()=>{input.value="";render();suggestions.hidden=true;input.focus()};document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{input.value=b.dataset.q;render(input.value);suggestions.hidden=true;document.querySelector("#explore").scrollIntoView({behavior:"smooth"})});document.querySelector("#menuBtn").onclick=()=>{const n=document.querySelector("#nav");n.style.display=n.style.display==="flex"?"none":"flex"};document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();input.focus()}});render();